#
# migration YAML file
#
UP:
  queries:
    - DROP TABLE `accounts`, `answers`, `groups`, `guests`, `hosts`, `polls`, `questions`, `roles`,  `users`, `schema_migrations`;

    - |
        CREATE TABLE IF NOT EXISTS `accounts` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `company_name` varchar(100) NOT NULL,
            `address` varchar(50) DEFAULT NULL,
            `zipcode` varchar(20) DEFAULT NULL,
            `city` varchar(50) DEFAULT NULL,
            `country` varchar(50) DEFAULT NULL,
            `phone` varchar(50) DEFAULT NULL,
            `mobile` varchar(50) DEFAULT NULL,
            `fax` varchar(50) DEFAULT NULL,
            `ust_id` varchar(50) DEFAULT NULL,
            `host_id` int(11) unsigned NOT NULL,
            `subdomain` varchar(100) NOT NULL,
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

    - |
        INSERT INTO `accounts` (`id`, `company_name`, `address`, `zipcode`, `city`, `country`, `phone`, `mobile`, `fax`, `ust_id`, `host_id`, `subdomain`, `created`, `modified`, `deleted`) VALUES
            (1, 'guestify Headquarters', 'Hansaring 4', '50670', 'Köln', 'Deutschland', NULL, NULL, NULL, NULL, 0, 'backend', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (2, 'Haxenhaus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'haxenhaus', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0);

    - |
        CREATE TABLE IF NOT EXISTS `answers` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `poll_id` int(11) unsigned NOT NULL,
            `guest_id` int(11) unsigned NOT NULL,
            `question_id` int(11) unsigned NOT NULL,
            `rating` int(5) NOT NULL,
            `ip` varchar(50) NOT NULL,
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

    - |
        CREATE TABLE IF NOT EXISTS `groups` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `poll_id` int(11) unsigned NOT NULL,
            `locale` varchar(3) NOT NULL,
            `name` varchar(50) NOT NULL,
            `order` int(11) unsigned NOT NULL,
            `status` tinyint(1) unsigned NOT NULL DEFAULT '1',
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

    - |
        INSERT INTO `groups` (`id`, `poll_id`, `locale`, `name`, `order`, `status`, `created`, `modified`, `deleted`) VALUES
            (1, 1, 'eng', 'Food and Beverages', 1, 1, '2013-11-16 00:00:00', '2013-11-16 00:00:00', 0),
            (2, 1, 'eng', 'Restaurant', 2, 1, '2013-11-16 00:00:00', '2013-11-16 00:00:00', 0),
            (3, 1, 'eng', 'Staff', 3, 1, '2013-11-16 00:00:00', '2013-11-16 00:00:00', 0),
            (4, 1, 'deu', 'Essen & Getränke', 1, 1, '2013-11-22 18:39:47', '2013-11-22 18:39:47', 0),
            (5, 1, 'deu', 'Restaurant', 2, 1, '2013-11-22 18:39:47', '2013-11-22 18:39:47', 0),
            (6, 1, 'deu', 'Service', 3, 1, '2013-11-22 18:39:47', '2013-11-22 18:39:47', 0);

    - |
        CREATE TABLE IF NOT EXISTS `guests` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `poll_id` int(11) unsigned NOT NULL,
            `pin` varchar(10) NOT NULL,
            `ip` varchar(50) NOT NULL,
            `guest_type` int(3) unsigned NOT NULL,
            `visit_time` int(3) unsigned NOT NULL,
            `user_agent` varchar(200) DEFAULT NULL,
            `referrer` varchar(200) DEFAULT NULL,
            `language` varchar(50) DEFAULT NULL,
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

    - |
        CREATE TABLE IF NOT EXISTS `hosts` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `account_id` int(11) unsigned NOT NULL,
            `name` varchar(100) NOT NULL,
            `locale` varchar(3) NOT NULL,
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

    - |
        INSERT INTO `hosts` (`id`, `account_id`, `name`, `locale`) VALUES
            (1, 2, 'Haxenhaus', 'deu');

    - |
        CREATE TABLE IF NOT EXISTS `polls` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `account_id` int(11) unsigned NOT NULL,
            `host_id` int(11) unsigned NOT NULL,
            `name` varchar(100) NOT NULL,
            `code` varchar(10) DEFAULT NULL,
            `status` int(3) unsigned NOT NULL,
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

    - |
        INSERT INTO `polls` (`id`, `account_id`, `host_id`, `name`, `code`, `status`, `created`, `modified`, `deleted`) VALUES
            (1, 2, 1, 'Feedback', '12345', 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0);

    - |
        CREATE TABLE IF NOT EXISTS `questions` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `account_id` int(11) unsigned NOT NULL,
            `host_id` int(11) unsigned NOT NULL,
            `poll_id` int(11) unsigned NOT NULL,
            `group_id` int(11) unsigned NOT NULL,
            `order` int(11) unsigned NOT NULL,
            `locale` varchar(3) NOT NULL,
            `question` varchar(100) NOT NULL,
            `scale` int(5) unsigned NOT NULL,
            `status` tinyint(1) unsigned NOT NULL DEFAULT '1',
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=23 ;

    - |
        INSERT INTO `questions` (`id`, `account_id`, `host_id`, `poll_id`, `group_id`, `order`, `locale`, `question`, `scale`, `status`, `created`, `modified`, `deleted`) VALUES
            (1, 2, 1, 1, 1, 1, 'eng', 'Range of food', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (2, 2, 1, 1, 1, 2, 'eng', 'Quality of food', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (3, 2, 1, 1, 1, 3, 'eng', 'Presentation of food', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (4, 2, 1, 1, 1, 4, 'eng', 'Range of beverages and wines', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (5, 2, 1, 1, 2, 1, 'eng', 'Ambience & decor', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (6, 2, 1, 1, 2, 2, 'eng', 'Waiting time', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (7, 2, 1, 1, 2, 3, 'eng', 'Value for money', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (8, 2, 1, 1, 3, 1, 'eng', 'Friendliness', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (9, 2, 1, 1, 3, 2, 'eng', 'Competence', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (10, 2, 1, 1, 3, 3, 'eng', 'Flexibility', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (11, 2, 1, 1, 3, 4, 'eng', 'Service', 4, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (12, 2, 1, 1, 4, 1, 'deu', 'Angebot der Speisen', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (13, 2, 1, 1, 4, 2, 'deu', 'Qualität der Speisen', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (14, 2, 1, 1, 4, 3, 'deu', 'Präsentation', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (15, 2, 1, 1, 4, 4, 'deu', 'Getränke-/Weinangebot', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (16, 2, 1, 1, 5, 1, 'deu', 'Ambiente und Dekoration', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (17, 2, 1, 1, 5, 2, 'deu', 'Wartezeiten', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (18, 2, 1, 1, 5, 3, 'deu', 'Preis-/Leistungsverhältnis', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (19, 2, 1, 1, 6, 1, 'deu', 'Freundlichkeit', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (20, 2, 1, 1, 6, 2, 'deu', 'Kompetenz', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (21, 2, 1, 1, 6, 3, 'deu', 'Flexibilität', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0),
            (22, 2, 1, 1, 6, 4, 'deu', 'Serviceleistungen', 4, 1, '2013-11-22 18:42:45', '2013-11-22 18:42:45', 0);

    - |
        CREATE TABLE IF NOT EXISTS `roles` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `name` varchar(20) NOT NULL,
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

    - |
        INSERT INTO `roles` (`id`, `name`) VALUES
            (1, 'Admin'),
            (2, 'Client');

    - |
        CREATE TABLE IF NOT EXISTS `schema_migrations` (
            `version` int(10) unsigned NOT NULL DEFAULT '0',
            `datetime` int(10) unsigned NOT NULL DEFAULT '0'
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    - |
        INSERT INTO `schema_migrations` (`version`, `datetime`) VALUES
            (1384705509, 1384705812);

    - |
        CREATE TABLE IF NOT EXISTS `users` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `account_id` int(11) unsigned NOT NULL,
            `role_id` int(11) unsigned NOT NULL,
            `gender` tinyint(1) unsigned NOT NULL,
            `lastname` varchar(100) NOT NULL,
            `firstname` varchar(100) NOT NULL,
            `email` varchar(200) NOT NULL,
            `password` varchar(100) NOT NULL,
            `last_login` datetime DEFAULT NULL,
            `status` int(3) unsigned NOT NULL,
            `activation_hash` varchar(100) DEFAULT NULL,
            `valid_until` datetime DEFAULT NULL,
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

    - |
        INSERT INTO `users` (`id`, `account_id`, `role_id`, `gender`, `lastname`, `firstname`, `email`, `password`, `last_login`, `status`, `activation_hash`, `valid_until`, `created`, `modified`, `deleted`) VALUES
            (1, 1, 1, 0, 'Admin', 'Admin', 'admin@guestify.net', 'XXX', NULL, 1, NULL, NULL, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0),
            (2, 2, 2, 0, 'Haxenhaus', 'Admin', 'haxenhaus@guestify.net', 'XXX', NULL, 1, NULL, NULL, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0);


DOWN:
  queries:
    - DROP TABLE `accounts`, `answers`, `groups`, `guests`, `hosts`, `polls`, `questions`, `roles`,  `users`;