#
# migration YAML file
#
UP:
  queries:
    - ALTER TABLE  `targets` ADD  `timezone` VARCHAR( 100 ) NOT NULL DEFAULT  'Europe/Brussels' AFTER  `country_id` ;
        

DOWN:
  queries:
    - ALTER TABLE `targets` DROP `timezone`;