#
# migration YAML file
#
UP:
  queries:
    - |
        INSERT INTO `drafts` (`id`, `name_eng`, `name_deu`, `status`, `created`, `modified`, `deleted`) VALUES
            (1, 'Restaurant 1', 'Restaurant 1', 1, NOW(), NOW(), 0),
            (2, 'Restaurant 2', 'Restaurant 2', 1, NOW(), NOW(), 0),
            (3, 'Restaurant 3', 'Restaurant 3', 1, NOW(), NOW(), 0),
            (4, 'Bistro', 'Bistro', 1, NOW(), NOW(), 0),
            (5, 'Café', 'Café', 1, NOW(), NOW(), 0),
            (6, 'Bar', 'Bar', 1, NOW(), NOW(), 0);

    - |
        INSERT INTO `drafts_groups` (`id`, `draft_id`, `name_eng`, `name_deu`, `position`, `created`, `modified`, `deleted`) VALUES
            (1, 1, 'Food & Drinks', 'Essen & Getränke', 1, NOW(), NOW(), 0),
            (2, 1, 'Restaurant', 'Restaurant', 2, NOW(), NOW(), 0),
            (3, 1, 'Service', 'Service', 3, NOW(), NOW(), 0),
            (4, 2, 'Standard', 'Standard', 1, NOW(), NOW(), 0),
            (5, 3, 'Food Quality', 'Qualität vom Essen', 1, NOW(), NOW(), 0),
            (6, 3, 'Service Quality', 'Servicequalität', 1, NOW(), NOW(), 0),
            (7, 3, 'Price levels', 'Service', 1, NOW(), NOW(), 0),
            (8, 4, 'Survey', 'Umfrage', 1, NOW(), NOW(), 0),
            (9, 5, 'Survey', 'Umfrage', 1, NOW(), NOW(), 0),
            (10, 6, 'Survey', 'Umfrage', 1, NOW(), NOW(), 0);

    - |
        INSERT INTO `drafts_groups_questions` (`id`, `draft_id`, `drafts_group_id`, `question_eng`, `question_deu`, `scale`, `position`, `created`, `modified`, `deleted`) VALUES
            (NULL, 1, 1, 'Range of food', 'Angebot der Speisen', 4, 1, NOW(), NOW(), 0),
            (NULL, 1, 1, 'Quality of food', 'Qualität der Speisen', 4, 2, NOW(), NOW(), 0),
            (NULL, 1, 1, 'Presentation', 'Präsentation', 4, 3, NOW(), NOW(), 0),
            (NULL, 1, 1, 'Range of beverages and wines', 'Getränke-/Weinangebot', 4, 4, NOW(), NOW(), 0),
            (NULL, 1, 2, 'Ambience & decor', 'Ambiente & Dekoration', 4, 1, NOW(), NOW(), 0),
            (NULL, 1, 2, 'Waiting time', 'Wartezeiten', 4, 2, NOW(), NOW(), 0),
            (NULL, 1, 2, 'Value for money', 'Preis-/Leistungsverhältnis', 4, 3, NOW(), NOW(), 0),
            (NULL, 1, 3, 'Friendliness', 'Freundlichkeit', 4, 1, NOW(), NOW(), 0),
            (NULL, 1, 3, 'Competence', 'Kompetenz', 4, 2, NOW(), NOW(), 0),
            (NULL, 1, 3, 'Flexibility', 'Flexibilität', 4, 3, NOW(), NOW(), 0),
            (NULL, 1, 3, 'Service', 'Serviceleistungen', 4, 4, NOW(), NOW(), 0),
            (NULL, 2, 4, 'Taste', 'Geschmack', 6, 1, NOW(), NOW(), 0),
            (NULL, 2, 4, 'Look', 'Optik', 6, 2, NOW(), NOW(), 0),
            (NULL, 2, 4, 'Waiting time', 'Wartezeit', 6, 3, NOW(), NOW(), 0),
            (NULL, 2, 4, 'Service', 'Personal', 6, 4, NOW(), NOW(), 0),
            (NULL, 2, 4, 'Atmosphere', 'Atmosphäre', 6, 5, NOW(), NOW(), 0),
            (NULL, 2, 4, 'Overall Impression', 'Gesamteindruck', 6, 6, NOW(), NOW(), 0),
            (NULL, 3, 5, 'Food is fresh', 'Speisen sind frisch', 5, 1, NOW(), NOW(), 0),
            (NULL, 3, 5, 'The menu is diverse', 'Menü ist vielfältig', 5, 2, NOW(), NOW(), 0),
            (NULL, 3, 5, 'Dishes are well cooked', 'Gerichte sind gut gekocht', 5, 3, NOW(), NOW(), 0),
            (NULL, 3, 6, 'Orders are taken without delay', 'Bestellung ist schnell erfasst', 5, 1, NOW(), NOW(), 0),
            (NULL, 3, 6, 'Waiters are well-mannered', 'Bedienung ist höflich', 5, 2, NOW(), NOW(), 0),
            (NULL, 3, 6, 'Tables are clean', 'Tische sind sauber', 5, 3, NOW(), NOW(), 0),
            (NULL, 3, 6, 'Food is served impeccably', 'Das Essen ist tadellos serviert', 5, 4, NOW(), NOW(), 0),
            (NULL, 3, 6, 'Restaurant atmosphere is pleasant', 'Restaurant Atmosphäre ist angenehm', 5, 5, NOW(), NOW(), 0),
            (NULL, 3, 7, 'Prices are acceptable', 'Preise sind akzeptabel', 5, 1, NOW(), NOW(), 0),
            (NULL, 3, 7, 'Value for money', 'Preis-/Leistungsverhältnis', 5, 2, NOW(), NOW(), 0),
            (NULL, 4, 8, 'Choice of food', 'Auswahl Essen', 6, 1, NOW(), NOW(), 0),
            (NULL, 4, 8, 'Quality of Food', 'Qualität vom Essen', 6, 2, NOW(), NOW(), 0),
            (NULL, 4, 8, 'Freshness', 'Frische', 6, 3, NOW(), NOW(), 0),
            (NULL, 4, 8, 'Service', 'Personal', 6, 4, NOW(), NOW(), 0),
            (NULL, 4, 8, 'Price', 'Preis', 6, 5, NOW(), NOW(), 0),
            (NULL, 4, 8, 'Overall Impression', 'Gesamteindruck', 6, 6, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Selection of coffee', 'Auswahl Kaffee', 6, 1, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Quality of coffee', 'Qualität des Kaffees', 6, 2, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Freshness', 'Frische', 6, 3, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Creativity', 'Kreativität', 6, 4, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Service', 'Personal', 6, 5, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Price', 'Preis', 6, 6, NOW(), NOW(), 0),
            (NULL, 5, 9, 'Overall Impression', 'Gesamteindruck', 6, 7, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Choice of drinks', 'Auswahl Getränken', 6, 1, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Quality of drinks', 'Qualität der Getränke', 6, 2, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Creativity', 'Kreativität', 6, 3, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Ambiance', 'Ambiente', 6, 4, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Crowd', 'Publikum', 6, 5, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Music', 'Musik', 6, 6, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Service', 'Personal', 6, 7, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Price', 'Preis', 6, 8, NOW(), NOW(), 0),
            (NULL, 6, 10, 'Overall Impression', 'Gesamteindruck', 6, 9, NOW(), NOW(), 0);


DOWN:
  queries:
    - TRUNCATE `drafts`;
    - TRUNCATE `drafts_groups`;
    - TRUNCATE `drafts_groups_questions`;
