#
# migration YAML file
#
UP:
  queries:
    - |
        CREATE TABLE `targets` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `category_id` int(11) unsigned NOT NULL,
            `name` varchar(300) DEFAULT NULL,
            `address` varchar(200) DEFAULT NULL,
            `location` varchar(200) DEFAULT NULL,
            `zipcode` varchar(50) DEFAULT NULL,
            `city` varchar(100) DEFAULT NULL,
            `district` varchar(200) DEFAULT NULL,
            `state_id` int(11) unsigned DEFAULT NULL,
            `country_id` int(11) unsigned NOT NULL DEFAULT '1',
            `phone` varchar(50) DEFAULT NULL,
            `fax` varchar(50) DEFAULT NULL,
            `email` varchar(200) DEFAULT NULL,
            `web` varchar(500) DEFAULT NULL,
            `scraper` varchar(100) DEFAULT NULL,
            `source_url` varchar(500) DEFAULT NULL,
            `prepared` tinyint(1) unsigned NOT NULL DEFAULT '0',
            `transfer` tinyint(1) unsigned NOT NULL DEFAULT '0',
            `account_id` int(11) unsigned NOT NULL DEFAULT '0',
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DOWN:
  queries:
    - DROP TABLE targets;
