#
# migration YAML file
#
UP:
  queries:
    - |
        CREATE TABLE `weathers` (
            `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `date` date NOT NULL,
            `lat` varchar(50) NOT NULL,
            `lng` varchar(50) NOT NULL,
            `city` varchar(200) NOT NULL,
            `zipcode` varchar(50) NOT NULL,
            `country_id` int(11) unsigned NOT NULL,
            `data` longtext NOT NULL,
            `created` datetime NOT NULL,
            `modified` datetime NOT NULL,
            `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
            PRIMARY KEY (`id`)
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DOWN:
  queries:
    - DROP TABLE weathers;