#
# migration YAML file
#
UP:
  queries:
    - ALTER TABLE `polls` ADD `notify_on_answer` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' AFTER `text`;


DOWN:
  queries:
    - ALTER TABLE `polls` DROP `notify_on_answer`;